# fly.toml app configuration file generated for autopictura on 2025-07-22
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autopictura'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  SHOPIFY_APP_URL="https://autopictura.fly.dev"
  APP_URL="https://autopictura.fly.dev"
  HOST="0.0.0.0"
  NODE_ENV="production"
  APP_ENV="production"
  # Database configuration - replace with actual values when deploying
  TURSO_CONNECTION_URL="libsql://your-production-database-url.turso.io"
  TURSO_AUTH_TOKEN="your-production-auth-token"
