# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dabfce4798337ee21f0a8970fb76757f"
name = "[DEV] AI Pet Converter"
handle = "ai-generator-app"
application_url = "https://ai-app.eu-1.sharedwithexpose.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,read_themes,write_app_proxy"

[auth]
redirect_urls = ["https://ai-app.eu-1.sharedwithexpose.com/auth/callback", "https://ai-app.eu-1.sharedwithexpose.com/auth/shopify/callback", "https://ai-app.eu-1.sharedwithexpose.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://ai-app.eu-1.sharedwithexpose.com"
prefix = "tools"
subpath = "ai-studio"
