# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dabfce4798337ee21f0a8970fb76757f"
name = "[DEV] Autopictura"
handle = "autopictura-dev"
application_url = "https://drawing-printed-xml-sg.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://excuse-np-wisconsin-tried.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://excuse-np-wisconsin-tried.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_app_proxy,write_orders,write_products"

[auth]
redirect_urls = ["https://drawing-printed-xml-sg.trycloudflare.com/auth/callback", "https://drawing-printed-xml-sg.trycloudflare.com/auth/shopify/callback", "https://drawing-printed-xml-sg.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://drawing-printed-xml-sg.trycloudflare.com"
subpath = "autopictura"
prefix = "tools"

[pos]
embedded = false
